name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
      
      
env:
  REGISTRY: docker.io
  IMAGE_PREFIX: ${{ secrets.DOCKERHUB_USERNAME }}
  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2
      
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'
          
      - name: Install dependencies
        run: |
          dotnet restore ./src/Booking.System/Booking.System.LoyaltyService/Booking.System.LoyaltyService.csproj
          dotnet restore ./src/Booking.System/Booking.System.PaymentService/Booking.System.PaymentService.csproj
          dotnet restore ./src/Booking.System/Booking.System.ReservationService/Booking.System.ReservationService.csproj
          dotnet restore ./src/Booking.System/Booking.System.Gateway/Booking.System.Gateway.csproj

      - name: Build
        run: |
          dotnet publish ./src/Booking.System/Booking.System.LoyaltyService/Booking.System.LoyaltyService.csproj -c Release
          dotnet publish ./src/Booking.System/Booking.System.PaymentService/Booking.System.PaymentService.csproj -c Release
          dotnet publish ./src/Booking.System/Booking.System.ReservationService/Booking.System.ReservationService.csproj -c Release
          dotnet publish ./src/Booking.System/Booking.System.Gateway/Booking.System.Gateway.csproj -c Release

      - name: Run Tests
        run: dotnet test ./src/Booking.System/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          docker compose -f docker-compose.build.yml build
          docker compose -f docker-compose.build.yml push

  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    needs: build 
    steps:
      - uses: actions/checkout@v4
      # TODO deploy to k8s with liveness and readyness probes
      
      - name: Setup Minikube
        uses: medyagh/setup-minikube@master

      - name: Check Minikube Cluster
        run: |
          minikube status
          kubectl get pods -A
          
      - name: Create Namespace
        run: kubectl create namespace spirit 
        
        
      - name: Deploy DB and services
        run: |
          kubectl get namespace
          
          cd k8s
          
          helm delete postgres --namespace spirit --ignore-not-found
          helm delete services --namespace spirit --ignore-not-found
          
          helm install -n spirit postgres ./postgres
          helm install -n spirit services ./services
          
      - name: Enable Ingress in Minikube
        run: |
          minikube addons enable ingress
          
          kubectl wait --namespace ingress-nginx \
            --for=condition=ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=300s
            
      - name: Wait 15s
        uses: jakejarvis/wait-action@master
        with:
          time: '15s'
          
      - name: Deploy Ingress
        run: |
          kubectl apply -f k8s/ingress.yaml
          
          
          minikube tunnel &
          TUNNEL_PID=$!
          echo "TUNNEL_PID=$TUNNEL_PID" >> $GITHUB_ENV
          
          sleep 30
          
          kubectl get ingress -n spirit -o wide
          
      
      - name: Initialize Databases
        run: |
          kubectl expose deployment postgres -n spirit \
            --port=5432 \
            --target-port=5432 \
            --name=postgres
          
          sleep 5

          kubectl get svc -n spirit postgres -o wide
          kubectl wait --namespace spirit --for=condition=ready pod -l app=postgres --timeout=300s
          
          echo "Initialize databases and schemas..."
          for script in 00-init-user.sql 01-create-databases.sql 02-reservations-schema.sql 03-payments-schema.sql 04-loyalties-schema.sql; do
            echo "Executing $script..."
            kubectl exec -n spirit deployment/postgres -- \
              psql -U postgres -f /docker-entrypoint-initdb.d/$script
          done
    
          echo "Database initialization completed"
      
      - name: Check 
        if: always()
        run: |          
          kubectl get pods -n spirit -o wide
          kubectl get all -n spirit -o wide
          kubectl get services -n spirit -o wide
          
          kubectl logs -f deployment.apps/loyalty -n spirit
          kubectl logs -f deployment.apps/payment -n spirit
          kubectl logs -f deployment.apps/reservation -n spirit
          kubectl logs -f deployment.apps/gateway -n spirit
      
      
      - name: Run Test Script
        run: |
          echo "=== Running test script ==="
          chmod +x ./scripts/test-script.sh
          ./scripts/test-script.sh v2 loyalty spirit

      
      - name: Cleanup Tunnel
        if: always()
        run: |
          if [ ! -z "$TUNNEL_PID" ]; then
            kill $TUNNEL_PID 2>/dev/null || true
          fi
      
      - name: Autograding
        uses: education/autograding@v1
        continue-on-error: true
